CREATE FUNCTION formato_de_id_cde(id INT)
RETURNS TEXT
AS
$$
  SELECT TO_CHAR(id,'FM000') || '-' || EXTRACT('Year' FROM CURRENT_DATE) || '-' || EXTRACT ( 'Year' FROM (CURRENT_DATE + 365) );
$$
LANGUAGE SQL
IMMUTABLE;

SELECT EXTRACT('Year' FROM CURRENT_DATE)
SELECT EXTRACT ( 'Year' FROM (CURRENT_DATE + 365) )
SELECT formato_de_id_cde(2)